Repository frequenz-floss/frequenz-dispatch-python, pull requests merged in 2024-10, with the labels that each got.

#67 Fix overwritten fix for sdk dependency
  pyproject.toml
Labels: part:tooling, part:dispatcher

#70 Extend `frequenz-sdk` dependency
  RELEASE_NOTES.md
  pyproject.toml
Labels: part:docs, part:tooling, part:dispatcher

#71 Fix recurrence
  RELEASE_NOTES.md
  src/frequenz/dispatch/_dispatch.py
Labels: part:docs, part:dispatcher
