Repository frequenz-floss/frequenz-dispatch-python, pull requests merged in 2024-05, with the labels that each got.

#26 Remove explicit dependency on sybil
  pyproject.toml
Labels: part:tooling, type:tech-debt

#22 Make `ready_to_execute` channel more general
  README.md
  RELEASE_NOTES.md
  src/frequenz/dispatch/__init__.py
  src/frequenz/dispatch/_dispatch.py
  src/frequenz/dispatch/_dispatcher.py
  src/frequenz/dispatch/_event.py
  src/frequenz/dispatch/actor.py
  tests/test_frequenz_dispatch.py
Labels: part:docs, part:tests, part:tooling, part:actor

#29 Don't recursively scan for pyproject.toml when calculating the cache key
  .github/workflows/ci.yaml
Labels: part:tooling

#30 Prepare release notes
  RELEASE_NOTES.md
Labels: part:docs

#31 Reset Release Notes after release
  RELEASE_NOTES.md
Labels: part:docs
