Repository frequenz-floss/frequenz-dispatch-python, pull requests merged in 2025-04, with the labels that each got.

#123 Update to repo-config 0.13
  .github/dependabot.yml
  .github/workflows/ci-pr.yaml
  .github/workflows/ci.yaml
  RELEASE_NOTES.md
  docs/_scripts/macros.py
  mkdocs.yml
  pyproject.toml
  tests/test_frequenz_dispatch.py
  tests/test_mananging_actor.py
Labels: part:docs, part:tests, part:tooling, part:dispatcher

#131 Expose src Dispatch for rare complex scenarios
  RELEASE_NOTES.md
  src/frequenz/dispatch/_actor_dispatcher.py
Labels: part:docs, part:dispatcher

#133 Prepare for release v0.6.1
  RELEASE_NOTES.md
Labels: part:docs, part:dispatcher

#136 Update `frequenz-sdk` dependency range to allow `v1.0.0-rc18xx`
  pyproject.toml
Labels: part:tooling, part:dispatcher

#137 Clear release notes
  RELEASE_NOTES.md
Labels: part:docs, part:dispatcher
